branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts: 
          - "Lint"
          - "Build"
      enforce_admins: false
      restrictions: null 